version: "3"
services:
  app:
    build:  
      context: ../..
      dockerfile: ./deployments/Dockerfile
    env_file: ../../.env
    networks:
      - pet_network
networks:
  pet_network:
    external: true