version: "3"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pet_db:/var/lib/postgresql/data
      - ./user_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pet_network
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis/redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - pet_network
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - pet_network
  kafka:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - pet_network
  ch_server:
    image: "yandex/clickhouse-server"
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
      - pet_network

volumes:
  pet_db:
  redis:
  pet_kafka:

networks:
  pet_network:
    external: true