// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package userapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUserRequest(ctx context.Context, in *AddUserInput, opts ...grpc.CallOption) (*AddUserOutput, error)
	DeleteUserRequest(ctx context.Context, in *DeleteUserInput, opts ...grpc.CallOption) (*DeleteUserOutput, error)
	GetListRequest(ctx context.Context, in *GetListInput, opts ...grpc.CallOption) (*GetListOutput, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUserRequest(ctx context.Context, in *AddUserInput, opts ...grpc.CallOption) (*AddUserOutput, error) {
	out := new(AddUserOutput)
	err := c.cc.Invoke(ctx, "/userapi.UserService/AddUserRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserRequest(ctx context.Context, in *DeleteUserInput, opts ...grpc.CallOption) (*DeleteUserOutput, error) {
	out := new(DeleteUserOutput)
	err := c.cc.Invoke(ctx, "/userapi.UserService/DeleteUserRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetListRequest(ctx context.Context, in *GetListInput, opts ...grpc.CallOption) (*GetListOutput, error) {
	out := new(GetListOutput)
	err := c.cc.Invoke(ctx, "/userapi.UserService/GetListRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	AddUserRequest(context.Context, *AddUserInput) (*AddUserOutput, error)
	DeleteUserRequest(context.Context, *DeleteUserInput) (*DeleteUserOutput, error)
	GetListRequest(context.Context, *GetListInput) (*GetListOutput, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) AddUserRequest(context.Context, *AddUserInput) (*AddUserOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserRequest not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserRequest(context.Context, *DeleteUserInput) (*DeleteUserOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserRequest not implemented")
}
func (UnimplementedUserServiceServer) GetListRequest(context.Context, *GetListInput) (*GetListOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListRequest not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_AddUserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userapi.UserService/AddUserRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUserRequest(ctx, req.(*AddUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userapi.UserService/DeleteUserRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserRequest(ctx, req.(*DeleteUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userapi.UserService/GetListRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetListRequest(ctx, req.(*GetListInput))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userapi.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserRequest",
			Handler:    _UserService_AddUserRequest_Handler,
		},
		{
			MethodName: "DeleteUserRequest",
			Handler:    _UserService_DeleteUserRequest_Handler,
		},
		{
			MethodName: "GetListRequest",
			Handler:    _UserService_GetListRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
